language: node_js
before_install:
  - "export CODECLIMATE_REPO_TOKEN="
install:
  - "npm install npm@~1.4.23 -g"
  - "npm install grunt-cli -g"
  - "npm install codeclimate-test-reporter -g"
  - "npm install"
script:
  - "grunt ci"
node_js:
  - "0.8"
  - "0.10"
